import { Work_Sans } from "next/font/google";
import "./globals.css";

const worksans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Uom Chess",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={worksans.style} className="bg-myBlack overflow-x-hidden">
        {children}
        
      </body>
    </html>
  );
}
